// Ingestion config, ported from the Python JobAlert config.yaml.
// Tuned to Shubham's résumé: MERN (Node/Express/React/Next.js) + AWS full-stack,
// ~3 yrs experience. A curated subset of the original company list — expand freely
// (full list lives in ~/JobAlert/config.yaml).

export const MAX_EXPERIENCE_YEARS = 4;

/** A job matches if its TITLE contains any of these (case-insensitive). */
export const KEYWORDS: readonly string[] = [
  "Full Stack",
  "Fullstack",
  "Full-Stack",
  "MERN",
  "Node",
  "React",
  "Next.js",
  "Frontend",
  "Front End",
  "Front-End",
  "Backend",
  "Back End",
  "Javascript",
  "Typescript",
  "Software Engineer",
  "Software Development Engineer",
  "SDE",
  "Web Developer",
];

/** Drop a job if its TITLE contains any of these (seniority / off-stack noise). */
export const EXCLUDE_TITLE_KEYWORDS: readonly string[] = [
  "staff",
  "principal",
  "lead",
  "director",
  "architect",
  "head of",
  "manager",
  "distinguished",
  "fellow",
  "vp ",
  "president",
  "intern",
  "salesforce",
  "sap ",
  "wordpress",
  "drupal",
  "magento",
  "embedded",
  "mainframe",
  "cobol",
  "sharepoint",
  ".net developer",
  "android developer",
  "ios developer",
  "qa engineer",
  "test engineer",
  "sdet",
];

/** In "multi" mode, the always-accept allow-list (India + named target hubs). */
export const LOCATIONS: readonly string[] = [
  "India",
  "Bengaluru",
  "Bangalore",
  "Hyderabad",
  "Pune",
  "Gurgaon",
  "Gurugram",
  "Noida",
  "Delhi",
  "Mumbai",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Indore",
  "Remote",
  "Global",
  "Worldwide",
  "Anywhere",
  "United States",
  "USA",
  "U.S.",
  "Japan",
  "Tokyo",
  "Europe",
  "United Kingdom",
  "London",
  "Germany",
  "Berlin",
  "Netherlands",
  "Amsterdam",
  "Ireland",
  "Dublin",
];

/** Company slugs per ATS. The slug is the last path segment of the careers URL.
 * Full list ported from JobAlert — Indian product/fintech companies first. */
export const COMPANIES = {
  greenhouse: [
    // — India —
    "razorpaysoftwareprivatelimited",
    "groww",
    "phonepe",
    "slice",
    "postman",
    "druva",
    "hackerrank",
    "turing",
    // — Global product w/ India offices —
    "stripe",
    "databricks",
    "okta",
    "rubrik",
    "cockroachlabs",
    "twilio",
    "mongodb",
    "elastic",
    "datadog",
    "cloudflare",
    "clickhouse",
    "fivetran",
    "gitlab",
    // — Big global product —
    "airbnb",
    "coinbase",
    "dropbox",
    "robinhood",
    "brex",
    "gusto",
    "samsara",
    "affirm",
    "chime",
    "discord",
    "reddit",
    "pinterest",
    "lyft",
    "instacart",
    "roblox",
    "asana",
    "sofi",
    "grafanalabs",
    "figma",
    "flexport",
  ],
  lever: [
    // — India —
    "cred",
    "meesho",
    "paytm",
    "zeta",
    "epifi",
    "porter",
    "mindtickle",
    // — Global —
    "mistral",
    "spotify",
    "palantir",
  ],
  ashby: [
    // — India —
    "navi",
    "sarvam",
    "atlan",
    // — Global product / dev-tools / AI —
    "snowflake",
    "confluent",
    "notion",
    "temporal",
    "openai",
    "cohere",
    "sierra",
    "decagon",
    "harvey",
    "watershed",
    "replit",
    "supabase",
    "posthog",
    "vanta",
    "zip",
    "cursor",
    "elevenlabs",
    "mercor",
    "moderntreasury",
  ],
} as const;

/** Workday careers-site URLs. Workday has no global directory, so each company
 * is its exact public careers URL — the scraper parses tenant/datacenter/site
 * out of it (`https://{tenant}.{dc}.myworkdayjobs.com/{site}`). To add a company,
 * open its Workday careers page and paste the URL here. All below are verified to
 * return the public jobs JSON and hire software engineers (incl. India offices). */
export const WORKDAY: readonly string[] = [
  "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
  "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site",
  "https://adobe.wd5.myworkdayjobs.com/external_experienced",
  "https://paypal.wd1.myworkdayjobs.com/jobs",
  "https://autodesk.wd1.myworkdayjobs.com/uni",
  "https://workday.wd5.myworkdayjobs.com/Workday",
];
